### ISSUE TITLE
Dart 2 runtime failures in tests

### ISSUE THREAD

**Issue by keertip** [dart-lang/protobuf#94]
See the following when running tests in Dart 2 mode,

```
type 'PbList<dynamic>' is not a subtype of type 'List<int>' in type cast where
    PbList is from package:protobuf/protobuf.dart
    List is from dart:core
    int is from dart:core
  
  dart:core                                                                                    Object._as
  ../..//protobuf/lib/src/protobuf/field_set.dart 268:57          _FieldSet._$getN
  ../../protobuf/lib/src/protobuf/generated_message.dart 298:22  GeneratedMessage.$_getN
```

**Comment by jakobr-google** [comment]
This was fixed in #97.

**Comment by keertip** [comment]
Still seeing the failure internally, looks like the change was not synced in. Will do so.
